---
- name: Prepare
  hosts: all
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false

    - name: Install epel-release
      include_role:
        name: stone-payments.epel
      when: ansible_os_family == "RedHat"

    - name: Install netstat (required by testinfra)
      yum:
        name: net-tools
        state: present
